name: Habit Reminder Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every day at 11 AM IST (5 AM UTC)
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Set to your Go version

      - name: Create .env File
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env

      - name: Verify .env File Exists
        run: ls -lah .env
        
      - name: Debug .env File (Safe)
        run: cat .env | sed 's/=.*$/=****/'
  
      - name: Install Dependencies
        run: go mod tidy

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: go run main.go

      - name: Run the Bot
        run: go run main.go
